motionName: hop

constraintList:
  - floatingBaseEom
  - torqueLimits
  - frictionCone
  - noContactMotion
  # - noSlipXY

weight:
  baseAccel: [1., 1., 1., 1., 1., 1.]
  com:        [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  contactForce: [0.0, 0.0, 0.0]
  SumFz: 0.25
  swingLeg: 0
  jointTorque: 0
  noContactMotion: [0.0, 0.0, 0.0]
  footZ: 0.

baseAccelTask:
  baseAcc_kp: [400., 400., 400., 100., 100., 100.]
  baseAcc_kd: [20., 20., 20., 10., 10., 10.]

comTask:
  com_kp: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  com_kd: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

swingLegTask:
  kp: 0
  kd: 0

stanceZTask:
  kp: 0
  kd: 0

# joint PD
jointKp: 10
jointKd: 0.5