motionName: hop

constraintList:
  - floatingBaseEom
  - torqueLimits
  - frictionCone
  - noContactMotion
  # - noSlipXY

weight:
  baseAccel: [0., 0., 0., 0., 0., 0.]
  com:       [0.1, 0.1, 0.5, 5.0, 5.0, 1.0]
  contactForce: [0.0, 0.0, 0.0]
  SumFz: 0.25
  swingLeg: 0
  jointTorque: 0
  noContactMotion: [0.0, 0.0, 0.0]
  footZ: 0.

baseAccelTask:
  baseAcc_kp: [0., 0., 0., 0., 0., 0.]
  baseAcc_kd: [0., 0., 0., 0., 0., 0.]

comTask:
  com_kp: [1.0, 9.0, 0.0, 0.0, 0.0, 0.0]
  com_kd: [10.0, 10.0, 20.0, 10.0, 10.0, 10.0]

swingLegTask:
  kp: 0
  kd: 0

stanceZTask:
  kp: 0
  kd: 0

# joint PD
jointKp: 10
jointKd: 0.5