motionName: lift_leg

constraintList:
  - floatingBaseEom
  - torqueLimits
  - frictionCone
  - noContactMotion
  # - noSlipXY

weight:
  baseAccel: 
    - 1.
    - 1.
    - 1.
    - 1.
    - 1.
    - 1.
  com:  
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  contactForce: 
    - 0.0
    - 0.0
    - 0.0
  SumFz: 0.25
  swingLeg: 10.
  jointTorque: 0
  noContactMotion:
    - 0.0
    - 0.0
    - 0.0

baseAccelTask:
  baseAcc_kp:
    - 400.0       # p_base_x
    - 400.0       # p_base_y
    - 400.0       # p_base_z
    - 400.0       # x
    - 400.0       # y
    - 400.0       # z
  baseAcc_kd:
    - 20.0      # vx
    - 20.0      # vy
    - 20.0      # vz
    - 20.0      # wx
    - 20.0      # wy
    - 20.0      # wz

comTask:
  com_kp:
    - 0.0       # p_base_x
    - 0.0       # p_base_y
    - 0.0       # p_base_z
    - 0.0       # x
    - 0.0       # y
    - 0.0       # z
  com_kd:
    - 0.0       # vx
    - 0.0       # vy
    - 0.0       # vz
    - 0.0       # wx
    - 0.0       # wy
    - 0.0       # wz

swingLegTask:
  kp: 400
  kd: 20

# joint PD
jointKp: 10
jointKd: 0.5