motionName: stand

baseAccelTask:
  baseAcc_kp:
    - 00.0       # p_base_x
    - 00.0       # p_base_y
    - 00.0       # p_base_z
    - 400.0       # x
    - 400.0       # y
    - 400.0       # z
  baseAcc_kd:
    - 0.0      # vx
    - 0.0      # vy
    - 0.0      # vz
    - 20.0      # wx
    - 20.0      # wy
    - 20.0      # wz

comAccelTask:
  comAcc_kp:
    - 9.0       # p_base_x
    - 9.0       # p_base_y
    - 9.0       # p_base_z
    - 0.0       # x
    - 0.0       # y
    - 0.0       # z
  comAcc_kd:
    - 3.0       # vx
    - 3.0       # vy
    - 3.0       # vz
    - 0.0       # wx
    - 0.0       # wy
    - 0.0       # wz

swingLegTask:
  kp: 350
  kd: 37

weight:
  baseAccel: 
    - 1.1
    - 1.1
    - 1.1
    - 1.1
    - 1.1
    - 1.1
  comAccel:  
    - 0.1
    - 0.1
    - 0.1
    - 1.0
    - 1.0
    - 1.0
  contactForce: 
    - 0.0
    - 0.0
    - 0.0
  SumFz: 0.25
  swingLeg: 0
  jointTorque: 0

# joint PD
jointKp: 10
jointKd: 0.5