# Whole body control
verbose: false
logInterval : 5

torqueLimitsTask:
  - 23.7     # HAA
  - 23.7     # HFE
  - 45.43    # KFE

frictionConeTask:
  frictionCoefficient: 0.3

# WeightedWbc
qpSolver: osqp      # osqp qpOASES

motionList:
  - stand
  - jump
  - lift_leg
  - hop

